name: Node.ts CI

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    DEV-BUILD:
        runs-on: ubuntu-latest
        environment: DEV

        strategy:
            matrix:
                node-version: [19.x]

        env:
            SERVER_PORT: 8081
            MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

        steps:
            - name: Check env
              run: echo $MONGO_DB_URL_DEV

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test
