# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.ts CI

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    DEV-BUILD:
        runs-on: ubuntu-latest
        environment: DEV

        strategy:
            matrix:
                node-version: [19.x]

        env:
            PORT: 8001
            MONGO_DB_URL_DEV: ${{ secrets.MONGO_DB_URL_DEV }}

        steps:
            - name: Check env
              run: echo $MONGO_DB_URL_DEV

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
